# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
