# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0002_auto_20170802_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdate',
            name='sickLeave',
            field=models.BooleanField(default=False),
        ),
    ]
