# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeApp', '0003_requestdate_sickleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdate',
            name='halfDay',
            field=models.BooleanField(default=False),
        ),
    ]
